<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BookShop.DataAccess\BookShop.DataAccess.csproj" />
    <ProjectReference Include="..\BookShop.Models\BookShop.Models.csproj" />
    <ProjectReference Include="..\BookShop.Utility\BookShop.Utility.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
